- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"
- name: "enhancement"
  color: "a2eeef"
  description: "New feature or request"
- name: "documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"
- name: "quantum-ai"
  color: "7057ff"
  description: "Related to quantum AI research"
